export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const LOAD_USERS = 'LOAD_USERS'
export const LOAD_BALANCE = 'LOAD_BALANCE'

export const PLAYER_LOADED = 'PLAYER_LOADED'
export const PLAYER_ERROR = 'PLAYER_ERROR'
export const BID_LOADED = 'BID_LOADED'
export const BIDS_LOADED = 'BIDS_LOADED'
export const OUTS_LOADED = 'OUTS_LOADED'
export const SET_PAUSE = 'SET_PAUSE'
export const LOAD_TEAMS = 'LOAD_TEAMS'
export const GET_UNDRAFTED = 'GET_UNDRAFTED'

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
